settings:
  enable-sounds: true
messages:
  prefix: "&8[&aOKits&8]"
  kits-cmd:
    created: "<prefix> &aYou have created the kit &d%s" 
    modified: "<prefix> &6You have modified the kit &d%s" 
    removed: "<prefix> &cYou have removed the kit &d%s" 
  recieved:
    message:
      - "&7&m+----------------------+"
      - ""
      - "&aYou has been recieved the kit &b&n%s"
      - ""
      - "&7&m+----------------------+"
    sound: "ENDERDRAGON_GROWL"