settings:
  enable-sounds: true
messages:
  prefix: "&8[&aOKits&8]"
  kits-cmd:
    created: "<prefix> &aYou have created the kit &d%s" 
    modified: "<prefix> &6You have modified the kit &d%s" 
    removed: "<prefix> &cYou have removed the kit &d%s"
    alreadyExist: "<prefix> &cThere is already a kit with the name &7&n%s"
    doesNotExist: "<prefix> &cThe &7&n%s &ckit does not exist"
    reset-kit: "<prefix> &dThe <kit> <player> kit has been restarted."
    reset-all: "<prefi> &dThe %s kits were reset."
  recieved:
    message:
      - "&7&m+----------------------+"
      - ""
      - "&aYou has been recieved the kit &b&n%s"
      - ""
      - "&7&m+----------------------+"
    sound: "ENDERDRAGON_GROWL"
  frozen: 
    message: "<prefix> &7You cannot claim this kit yet, you must wait &c%s&7."
editor-gui:
  title: "&6Editing %s kit"
  save-button:
    displayname: "&aSave kit"
    lore:
      - "&7Click here to save kit"
  cancel-button:
    displayname: "&cCancel"
    lore:
      - "&7Click here to cancel"
  frozen-button:
    displayname: "&cFrozen Settings"
    lore:
      - "&7Click to open frozen settings menu"
editor-frozen-gui:
  title: "&dFrozen Settings (%s)" 
  back-button:
    displayname: "&cBack to editor"
    lore:
      - "&7Click here to back to editor"
  add-time-button:
    displayname: "&a+"
    lore:
      - "&7Click to add time"
  remove-time-button:
    displayname: "&c-"
    lore:
      - "&7Click to remove time"
  months-button:
    displayname: "&aMoths"
    lore:
      - "&7Current: %s"
  days-button:
    displayname: "&aDays"
    lore:
      - "&7Current: %s"
  hours-button:
    displayname: "&aHours"
    lore:
      - "&7Current: %s"
  minutes-button:
    title: "&aMinutes"
    lore:
      - "&7Current: %s"
  seconds-button:
    displayname: "&aSeconds"
    lore:
      - "&7Current: %s"