settings:
  enable-sounds: true
messages:
  prefix: "&8[&aOKits&8]"
  kits-cmd:
    created: "<prefix> &aYou have created the kit &d%s" 
    modified: "<prefix> &6You have modified the kit &d%s" 
    removed: "<prefix> &cYou have removed the kit &d%s"
    alreadyExist: "<prefix> &cThere is already a kit with the name &7&n%s"
    doesNotExist: "<prefix> &cThe &7&n%s &ckit does not exist"
  recieved:
    message:
      - "&7&m+----------------------+"
      - ""
      - "&aYou has been recieved the kit &b&n%s"
      - ""
      - "&7&m+----------------------+"
    sound: "ENDERDRAGON_GROWL"
editor-gui:
  title: "&6Editing %s kit"
  save-button:
    displayname: "&aSave kit"
    lore:
      - "&7Click here to save kit"
      - ""
      - "&cTo cancel save press escape key"